use_frameworks!

target 'CoCentricCircleAnimationView_Example' do
  pod 'CoCentricCircleAnimationView', :path => '../'

  target 'CoCentricCircleAnimationView_Tests' do
    inherit! :search_paths

  end
end
